# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('desc', models.TextField()),
                ('precio', models.CharField(max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
